### ISSUE TITLE
Хочется обсудить ViewModelBase

### ISSUE THREAD

**Issue by Gankov** [QualitySolution/QSProjects#10]
Ребята давайте примем колегиальное решение, мне не нравится текущее решения в классе ViewModelBase, а именно прокидывание туда до самого низа интерфейса IInteractiveService.

Да я понимаю что возможно чем-то, (Хотя чем?) чуть более удобно внутри класса написать.. ShowInfoMessage(текст).
Но с другой стороны вызвать в ручную InteractiveMessage.ShowMessage(ImportanceLevel.Info, message), помоему не сильно сложнее. Если нравится интерфейс имено в виде ShowInfoMessage, то есть для статусов отдельные методы то может стоит IInteractiveService такие методы добавить?

Какие недостатки вижу у текущего решения:
- Вернее он один, мы тянем везде зависимость от IInteractiveService, даже там где в ней нет необходимости... То есть реально данный диалог посторенный на этой базе не вызывает не одного сообщения, а в зависимость мы ему этот интерфейс пихаем. Получается что абсолютно везде где мы создаем диалоги мы вынужнеды создавать класс IInteractiveService и передеавать его по ступенькам в низ. Для любого теста мы вынуждены будем подделывать этот интерфейс, хотя в тестируемом диалоге он возмоно не нужне, а тем более в тестируемом методе. Будет куча лишнего кода.

**Comment by Enzogord** [comment]
Полностью согласен, это решение было удобно когда я его в самый первый класс добавил, потом от него начались проблемы.

**Comment by Gankov** [comment]
Проблема в реализаци этого в необходимости иметь здесь https://github.com/QualitySolution/QSProjects/blob/787da8e42be54576e016f8f952754f24ee2c4437/QS.Project/ViewModels/TabViewModelBase.cs#L59 интерфейс, этот клас матрешкой вложен еще один раз.... Во все остальные классы. Поэтому без переделывания этого механизма, смысла мало убирать из класса на один уровень выше.
В новом подходе при создании ViewModel через NavigationManager у меня это заменено на вызов определенного эксепшена при создании ViewModel, нетворк менеджер его перехватывает и показывает пользователю сообщение. Я это могу реализовать и здесь, тогра проблема необхдимости здесь иметь сервис сообщений исчезнет. Но Получается что поломаются все места где ViewModel-и создаются вручную, а не через NavigationManager или любой другой механизм создания ViewModel например если в OpenTab где-то используется там тоже можно организовать перехвать эксепшена.

В общем что делаем? Еще кстати можно попробовать добавить просто перехвать этого экспешена через общий механизм который я сделал не так давно. https://github.com/QualitySolution/QSProjects/blob/787da8e42be54576e016f8f952754f24ee2c4437/QS.Project/ErrorReporting/CommonErrorHandlers.cs и выводить пользовател. сообщение. Но надо убедится что остальной код в этом случае не будет рушится, выкидыванием эксепшена до самого верха, теоритически все должно быть ок.

**Comment by Gankov** [comment]
Второй вариант перенести зависимость с класса на метод. То есть если какому-то ViewModel понадобится сообщить об ошибке созданию VM, он сможет иметь у себя в зависимостях IInteractiveService.
Хотя с третьей стороны зачем вообще этому VM этот метод, он сам может вызвать сообщения для пользователя и проставить тру у свойства. это займет 2 строчки, кода. Жду вашего мнения....

**Comment by Enzogord** [comment]
> Второй вариант перенести зависимость с класса на метод. То есть если какому-то ViewModel понадобится сообщить об ошибке созданию VM, он сможет иметь у себя в зависимостях IInteractiveService.

Во точно, вот этот вариант самый точный, передавать зависимость только когда надо показать сообщение о прерванной загрузке вкладки. И не придеться городить лишние конструкции, и зависимость мешаться не будет там где она не нужна.

> Хотя с третьей стороны зачем вообще этому VM этот метод, он сам может вызвать сообщения для пользователя и проставить тру у свойства. это займет 2 строчки, кода. Жду вашего мнения....

Думаю лучше через метод все же, чтобы одинаковые вызовы везде были.

**Comment by Gankov** [comment]
> Думаю лучше через метод все же, чтобы одинаковые вызовы везде были.
Дело в том что для тех ViewModel которые для открытия используют менеджер навигации задумато что тоже самое будет работать вот так:
`			if(currentPermissionService != null && !currentPermissionService.ValidateEntityPermission(typeof(TEntity)).CanRead)
				throw new AbortCreatingPageException($"У вас нет прав для просмотра документов типа: {typeof(TEntity).GetSubjectName()}", "Невозможно открыть журнал");`

Что позволит вызывать остановку создания вкладки в любом месте. Как тебе такой вариант?

**Comment by Enzogord** [comment]
Да эксепшн выглядит более логичнее для прерывания открытия вкладки. Я бы дополнил это решение тем что, обернуть бросок эксепшена, существующим методом AbortOpening(message, title). Тогда можно будет и оставить существующую структуру вызовов, и будет возможность использования в навигаторе. Нужно будет только поменять код проверки FailInitialize на отлов исключения.

**Comment by Gankov** [comment]
1 - Самое главное достоинство эксепшена в том что его не обязательно вызывать именно в классе, viewModel, его можно вызвать и где нибудь в другом месте в цепочке вызовов, при создании. Да в тех же журналах, например в классе твоего конфигуратора журнала. И вот как раз именно это главное достоинство и вообще понимание того что это эксепшен ты хочешь скрыть... 
2 - проблема со старыми методом еще в том что он предполагает возврат. То есть там будет return после этого. Хотя конечно это мелочи.
3 -  Самое главное, вообще то я с самого начала хотел тупо вставить внутрь метода этот эксепшен, аля совместимость со старыми вызовами и полез, ну и поле уже переделывать ITdiTab и notebook на перехват этого эксепшена, и понял, что это не будет работать.... Так как в новом менеджере ViewModel не позоляется в ручную создавать, поэтому эксепшен всегда можно прехватить. а в старом коде дофига где создается, вручную в класса. Поэтому тут возможне только глобальный перехват эксепшена. И вот собственно мой первый вопрос. и был. Насколько это правильно удобно для созданных класов, не вызовет ли это проблем.
Надеюсь понятно объяснил.
