### ISSUE TITLE
Предложение переименовать UoWTabViewModelBase

### ISSUE THREAD

**Issue by Gankov** [QualitySolution/QSProjects#11]
Сейчас есть класс UoWTabViewModelBase
Он реализует интерфейс вкладки с диалогом ITdiDialog что за собой тянет кучу необходимых для диалога методов, проверку, сохранено ли и можно ли закрыть, вкладку и т.п.
Но далеко не все кладки такие, многим это не надо.

В старых диалогах было: 
SingleUowTabBase  - базовый класс с реализацией только наличия у вкладки единого uow
SingleUowDialogBase - Реализация диалога как раз с этими методами которые есть в UoWTabViewModelBase

Вопрос, что лучше оставить  UoWTabViewModelBase как есть и рядом создать какой нибудь SingleUoWTabViewModelBase или 
Переименовать в DialogTabViewModelBase, а классу который будет реализовывать только добавление Uow дать название которое сейчас.

**Comment by Enzogord** [comment]
Я согласен, UoWTabViewModelBase переделать во вкладку которая просто хранит UoW и умеет его завершать при закрытии  (по сути функционал SingleUoW), но оставить название. И создать еще один класс DialogTabViewModelBase, который наследовать от UoWTabViewModelBase, и сделать реализацию ITDIDialog. Далее журналы как использвали так и пусть продолжают использвать очищенный уже UoWTabViewModelBase, а вкладки с диалогами перенаследовать от DialogTabViewModelBase.

**Comment by Gankov** [comment]
> методы для диалогов из UoWTabViewModelBase перенести в новый класс, а в самом UoWTabViewModelBase оставить только UoW. думаю так будет правильнее.

Это уже детали... Результат все равно один. быстрее будет переименовать, так автоматом все места использования переименуются.
