### ISSUE TITLE
Как вам идея реализовать библиотеку QS.Project.VododozLegacy

### ISSUE THREAD

**Issue by Gankov** [QualitySolution/QSProjects#121]
Куда я смогу переносить все код, который используется только в водовозе....
Просто реально хочется начать чистить нашу библиотеку от большого количества устаревших, классов.
И нет механизма это делать.

По идеии если библиотека будет подключена у вас в проекте то перенос не нужных в других проектах классов вас не затронет, если они передут в тех же пространствах имен.

**Comment by Gankov** [comment]
Кстати для этой либы можно будет снять мой обязательный ревь.

**Comment by Enzogord** [comment]
Можно попробовать. Что первое туда сейчас хочешь перенести?

**Comment by Gankov** [comment]
Ну вчера хотел вынести RepresentationJournalDialog
Потому что мешал переделывать интерфейс IJournalFilter.
Но потом вроде пришло решение о замене его.

Ну и в целом. На самом деле проблема вся в том что у нас в новых библиотеках уже накопилось очень много кода, который видимо не будет поддеживаться. Так как это были не удачные попытки прехода. Я хочу чтобы новые библиотеки QS.Project были все про ViewModel и новый подход. А старый постепенно выпилить совсем. Или вынести отдельно, например как старые наши либы доживающие свой век. Понятно что там код практически не будет обновлятся.

С теми же репрезентетион. Может выпилим их подбыстрее? в водовозе я так понимаю всего несколько диалогов на него завязано. А это в целом был просто промежуточный шаг в развитии.

Попробую обрисовать бизнес проблему. У нас отсутствует документация как класс, этим мы скоро займемся. И очень сложная струтура кода. Много классов, не очевидные зависимости компонентов. Как минимум 3 версии диалогов... Нет четкого деления на модули. Дополнительно незнакомый тулкит ГУИ. Все это приводит к тому что новые программисты внедряются очень долго. Я это проверил. Людям вообще сложно разобраться, относительно самостоятельно.
И это понятно. Потому что даже мне подчас сложно понять, как делать. Столько всего накручено. А для нас сейчас скорость разработки является клавным критерием. И получается что новым програмистам быстрее написать что-то свое простое не связанное с библиотеками чем разбираться. Если бы вы хоть чуть чуть включились в работу по зачистке... И вообще приведению кода к более простому и понятному виду.

**Comment by Gankov** [comment]
> Можно попробовать.
Ок. Тогда буду в следующий раз что-то рефакторить создам либу. 
А вообще все что хочу выпилить заношу сюда https://github.com/QualitySolution/QSProjects/projects/11 как задачи.

**Comment by Gankov** [comment]
Не актуально.
