### ISSUE TITLE
Атрибут оставлено для водовоза или проекта.

### ISSUE THREAD

**Issue by Gankov** [QualitySolution/QSProjects#13]
Предлагаю обсудить добавление какого нибудь либо атрибута, либо фразы в комментарии аля //FIXME //TODO и т.п. Для того чтобы понимать, почему мы оставляем не удаленным тот или иной класс, или функционал в общей библиотеке. Библиотека живет развивается, на смену некой старой функциональносит приходит новая. При этом старые варианты мы часто оставляем для совместимости, и это не плохо. Плохо что мы не совсем понимаем когда их нужно удалять. А удалять их нужно в конечном итоге, так как иначе будет захламление. И потом никто не разберестся.

Хочет иметь что-то стандартное, которое легко находится поиском или показывается в каких нибудь варнингах. Когда мы что-то оставляем, но понимаем что это остается только для одного проекта или нескольких проектов, чтобы их сейчас не переделывать. Получается что те кто делают конретный проект и будут ответсвенны за удаление этой функциональности из либы когда они пределаю это все у себя в проекте.

Варианты:
Атрибут - ищется легко, но что дальше? 
Специальный комментарий - Можно видеть в интерфейсе задач, кто нибудь ими пользуется?
Вообще создать атрибут сборки - Будет  то есть можно оборачивать весь код который остался под конкретный проект... Для других он даже не будет собираться.. удобный контроль

Может есть еще варианты?

**Comment by Enzogord** [comment]
Самое доступное я считаю //FIXME //TODO комментарии, проверять их я ни разу не искал и не закрывал, но писал во многих местах чтобы потом легче было понять.
Атрибут сборки - сразу нет, потому что контроль за всеми проектами есть только у тебя, тебе он может помочь а с нашей стороны только проблемы будут с ним.
Простой атрибут неплохой вариант, варнинги сразу видны будут, удобно.

**Comment by Gankov** [comment]
Варнинги возможно, в нутри [Obsolete("")] Просто писать что осталось только в таком то проекте...

Ты же понял, я хочу оставляя что-то в либе на кого-то повесить ответсвенность за удаление этого куска. Потому что оставлено не потому что везде это еще используется и потому что вот остался один проект который использует. Ну в вашем случае, вы можете отавлять комментарив, в проектах QS, а я дальше уже посмотрю. Я помечу для себя, если один. Просто я часто у себя в проектах подчищаю и переделываю. У вас это остается висеть. Я раньше водовоз правил и но эта практика должна прекращатся. И у меня есть старые проекты, которые я просто не хочу пересобирать, но они все завязаны на стрые варианты либ. Так что это фактически уже отделено.

С комментариями в туду. Проблема в том что туда никто не смотрит.
Вообще со всеми вариантами проблема в том что туда никто не смортит. А так будут конкретные куски либы, которые совервшенно явно помечены как только для водовоза, или только для старого чего нибудь у меня...

**Comment by Gankov** [comment]
Ну вообще не знаю я как лучше... Поэтому тему и поднял.

**Comment by Enzogord** [comment]
Да я уже начал больше к Obsolete склонятся, давай его использовать если все согласны.
А как мы поймем что код который мы хотим отметить не используется в других проектах?

**Comment by Gankov** [comment]
Ладно давайте через Obsolete,  я там просто буду указывать, что у меня нигде это больше не используется, значить вы как удалите, можете\должны подчистить. И так же наоборот, вы избавились от чего то старого, но оставили для совместимости, тоже в Obsolete посто пишите что в водовозе не используется можно безопасно удалить.
