### ISSUE TITLE
Передача Id и других параметров конструктору ViewModel

### ISSUE THREAD

**Issue by Gankov** [QualitySolution/QSProjects#14]
Сейчас экспериментирую со следующим шагом применения наших новых диалогов, а именно внедрением контейнера DI.
И есть совсем неоднозначный вопрос, на который хотелось бы услышать ваше мнение.
Как вы считаете более удобно правильно в диалог передавать параметры и в частности id сущьности.

Текущий предложенный Вадимом вариант с https://github.com/QualitySolution/QSProjects/blob/master/QS.Project/Project.Domain/EntityConstructorParam.cs помоему имеет слудующие проблемы:
- Класс по сути является просто передачей информации, не реализуя никакую полезную функциональность. То что он делает вполне можно было бы заменить одним параметром конструктора если использовать int? и одним опциональным RootUoW, так как на самом деле мало диалогов это реализуют.
- Имеет интерфейс, хотя не понятно, какую другую реализацию передающую RootUoW, new и id можно было бы реализовать...
- Хотя это возможно более понятные\красивые названия при передачи информации в конструктор. Наверно это плюс.

НО текущий вариант мне не очень нравится. В общем у меня есть сомнения, поэтому хотелось бы рассмотреть другие варианты...
И тут скорее стоит вопрос где и как лучше реализовывать создание uow, от этого и зависит как передавать и что передавать..
Какие вообще могут быть варианты:
1) Мы оставляем функциональность по созданию uow диалога втутри viewMode, и по сути внутри базового класа как собственно сделано сейчас, единственное чтобы перейти на DI, нам нужно будет дополнительно в нутрь прокидывать IUnitOfWorkFactory. Плюсы этого способа в том что на уровне диалога мы можем конторлировать как создается uow. но похоже так как это перенесено в базовый класс нам скорей всего это не надо. Но есть возможность на уровне диалога менять поведение создания uow.
2) Было бы вполне логично, нагрузить EntityConstructorParam, все таки какой то функциональностью, а в действительности зачем диалогу самому создавать Uow? тем более если есть дочерние uow, это усложнаяе логику базового класса. Создание uow мог бы делать сам EntityConstructorParam, таким каким ему прописали его делать. Тогда стало бы понятно, зачем класс, зачем интерфейс, и была бы реальная возможность поменять поведение. Этот вариан возможно поможет избежать прокидывания IUnitOfWorkFactory во все диалоги, а прокидывтать только в те которым это надо? и тут большой вопрос многие ли без него обойдутся. Возможно нет. И с другой стороны, у нас уже есть класс по созданию uow, называется фарбика...
3) Создавать uow снаружи, и передавать, в готовом виде. Вот в этом месте по мне так полностью закрывается вопрос с дочерними uow, потому что создавать дочерний uow или нет выбирает именно внешний код, так же он выбирает мы создаем uow для новой сущьности или подгружаем. Недостаток этого мне изначально казалось что это более громозкий код снаружи, с другой стороны UnitOfWorkFactory.CreateForRoot<TEntity>(5), не сильно длиннее EntityConstructorParam.ForOpen(5). Но недостатком этого способа видится необходисть знать тип создаваемой снаружи. Возможным плюсом то что диалог ничего не знает про создание uow, и вообще сущьности, это все котролируется внешней стороной, и в этом случае внешнему коду легко подсунуть предзаполненый Entity, например если мы создаем счет контрагента, то мы бы могли сразу снаружи заполнить поле контрагента или другие поля. С одной стороны, с другой, такие поля как контрагент, могут быть обязательными, и тогда их наверно лучше добавить в коструктор диалога.

У кого какое мнение?

**Comment by Gankov** [comment]
В процессе работы над внедрение DI, Пришел практически к однозначному выводу что варинат uow снаружи плох. Так как диалог сам должнен контролировать время жизни uow. То создавать его снаружи, не очень хорошая идея. Потому что тогда и котролировать закрытие надо снаружи, а это совсем не удобно.

**Comment by Enzogord** [comment]
Я склоняюсь ко 2 варианту больше, чтобы можно было контролировать UoW для конкретного диалога в отдельном месте. Возможно еще стоит дополнить этот класс возможностью передачи UoW извне, если будет необходимость работать с уже готовым снаружи uow (получается небольшое комбинирование с 3 вариантом).
Но абсолютно точно выносить логику создания из ViewModel классов. Сейчас у этих классов есть одна проблема - в них остается много логики для работы с сущностями. В идеале хочеться оставить в них только логику помогающую отображать информацию. А логика работы с сущностями или прочей информацией находилась в классах на подобии сервисов. И вот в эти сервисы как раз передавать этот новый класс управляющий UoW.

Резюмируя:
Отдельный класс типа EntityConstructorParam (только название поменять, потомучто очень уродское).
В него дать возможность передать готовый UoW либо фабрику по его созданию.
Реализовать в нем Dispose, чтобы можно было закрывать uow при уничтожении ViewModel (или других классов) в которых он будет использоваться.
Чтобы через него передавалась информация о Root сущности для которой он открыт.

**Comment by Gankov** [comment]
> Возможно еще стоит дополнить этот класс возможностью передачи UoW извне, если будет необходимость работать с уже готовым снаружи uow (получается небольшое комбинирование с 3 вариантом).

Вот тогда если это в какой то момент действительно понадобится, лучше создать отдельной реалицацией. Иначе опять же зачем интерфейс....

> Но абсолютно точно выносить логику создания из ViewModel классов. Сейчас у этих классов есть одна проблема - в них остается много логики для работы с сущностями. В идеале хочеться оставить в них только логику помогающую отображать информацию. А логика работы с сущностями или прочей информацией находилась в классах на подобии сервисов. И вот в эти сервисы как раз передавать этот новый класс управляющий UoW.

Звучит классно. Вот только какую конкретно лишнюю логику ты имеешь ввиду?
 
> Резюмируя:

Согласен со все, кроме последнего.

> Чтобы через него передавалась информация о Root сущности для которой он открыт.

Не совсем можеть быть понял, хочешь сказать, что диалог не должен напрямую обращатся к uow? Ну если это в контексте вынесения туда еще какой то функцианальности ... Ну хотя не знаю...

**Comment by Enzogord** [comment]
> Звучит классно. Вот только какую конкретно лишнюю логику ты имеешь ввиду?

первое что приходит в голову, это сохранение и валидация, но если покопаться может чтото еще есть

> Не совсем можеть быть понял, хочешь сказать, что диалог не должен напрямую обращатся к uow? Ну если это в контексте вынесения туда еще какой то функцианальности ... Ну хотя не знаю...
Речь идет о UoWGeneric, придумать чтото для того чтобы класс использующий этот новый объект для UoW знал что там есть Root определенного типа

**Comment by Gankov** [comment]
> первое что приходит в голову, это сохранение и валидация, но если покопаться может чтото еще есть

Ну сохранение очень часто  сложный процесс, в каждом диалоге, возможно нужно что-то еще делать, вызывать и т.п. Если это выносить, то как это переопределять... И что мы выйграем от выноса этой функциональности? Мы же не сможем наменить ее на что-то другое.
 
> Речь идет о UoWGeneric, придумать чтото для того чтобы класс использующий этот новый объект для UoW знал что там есть Root определенного типа

Вот сейчас еще раз подумав, понимаю, а зачем? что это дает. Так у класса понятная функциональность, это фабрика для создания uow для сущьности, на настройкам указанным внешним кодом. Я уже думаю что не должна она еще что-то делать.

**Comment by Gankov** [comment]
Давайте придумаем название класса. В целом мне уже желательно н новую реализацию иметь.
Мои варианты:
EntityUowConstructor
EntityUnitOfWorkConstructor
EntityUowFactory
EntityUnitOfWorkFactory

Не нравится что название не отражает того факта что параметры создания переданы... Получается если использовать слово Factory, то как будто там любой Entity Создать можно.

**Comment by Gankov** [comment]
EntityUowBuilder
UowForEntityBuilder
?

**Comment by Enzogord** [comment]
Он не только создает же, он его будет держать, предоставлять по требованию, пересоздавать.
Может быть EntityUoWController?

**Comment by Gankov** [comment]
Просто пока не вижу смысла. Иметь в нем ещё какую то функциональность. Тот же диспоз. Зачем его выносить? Что это даст? Не приходит ничего в голову на какую другую реализацию это можно было бы заменить или что-то туда добавить кроме uow.dispose. Зато это явно усложнить читаемость этого места. Этот класс где ещё можно будет использовать? Как контролёр, потенциально наверно да. А по факту? Что тогда в этом базовом классе останется? В той реализации к которой я сейчас стремлюсь. Нет ничего про вкладки...

**Comment by Gankov** [comment]
Я вот сейчас конкретно посмотрел этот класс, что там можно вынести в этот контроллер я совсем не понимаю? Если это будет билдер, то его можно будет потенциально переиспользовать в другом месте. То есть там, где надо создать Uow для сущьности, но не сразу а по запросу. Тут для меня понятное назначение. Я вот скорей думаю, нужно ли этому классу знать тип сущьности. Потому что при текущем использовании не нужно, это лишняя писанина при создании класса. ибо у диалога есть этот тип. С одной стороны, с другой, при попытке переиспользвать? предположительно нужно. Вот опять же, мне кажется во всех таких случаях не надо заранее создавать каких-то сущьностей... Пока нет конкретного варианта использвания.

**Comment by Enzogord** [comment]
Ты имеешь ввиду не давать знать о сущностей билдеру, а UoWGeneric создавать при вызове обобщеного метода типа CreateUoW<TEntity> передавая тип из класса который уже знает о типе сущности?
Если так, то да так даже лучше будет, согласен.

**Comment by Gankov** [comment]
Да, так. По сути оставив внутренности этого класса полностью такми же, просто перенести туда метод для создания uow из базового класса диалога.
По поводу того что стоит делать именно билдер согласен? Я не могу придумать его использования как контролеер.

**Comment by Enzogord** [comment]
Полностью избавились от старого класса EntityConstructorParam, думаю можно закрывать обсуждение?
