### ISSUE TITLE
Пространство имен водовоза затесавшеся в библиотеку.

### ISSUE THREAD

**Issue by Gankov** [QualitySolution/QSProjects#157]
Недавно обнаружил что следующие классы находятся в простнастве имен Vodovoz
думаю это ошибка.

- https://github.com/QualitySolution/QSProjects/blob/master/QS.Project/Project.Journal/FilterableSingleEntityJournalViewModelBase.cs
- https://github.com/QualitySolution/QSProjects/blob/master/Modules/QSBanks/Representations/AccountsVM.cs
- https://github.com/QualitySolution/QSProjects/blob/master/QS.Project.Gtk/Widgets.GtkUI/NullableCheckButton.cs

**Comment by Enzogord** [comment]
Исправлено в https://github.com/QualitySolution/QSProjects/pull/175
