### ISSUE TITLE
Насколько нам вообще в журнале надо это поле NodeType?

### ISSUE THREAD

**Issue by Gankov** [QualitySolution/QSProjects#25]
https://github.com/QualitySolution/QSProjects/blob/787da8e42be54576e016f8f952754f24ee2c4437/QS.Project/Project.Journal/JournalViewModelBase.cs#L20

Оно реально помоему нигде не используется, при этом этот клас заставляет всех наследников его реализовывать.
С одной стороны оно потенциально конечно может понадобится, но только поненциально. Потому что в жизне не очень понятно зачем. Оно может понадобится только там где с журналом работаю, так что не знаю что это за журнал. А это как то мало вероятно, при текущей схеме. Кто что думает?

**Comment by opopve** [comment]
Ну если есть сомнения в ненужности свойства, то может не делать его абстрактным? И в наследниках, реализовывать уже по необходимости.

**Comment by Gankov** [comment]
Ну видимо так не получится... Если убрать абстрактный тогда еще меньше понятно зачем его реализовывать.

**Comment by Enzogord** [comment]
Идея какая была: так как журнал для вьюшки представляеться только классом JournalViewModelBase, нужно было знать что за тип у Items. В итоге это все как то стало не нужным со временем. Можно удалить думаю, если понадобиться там уже решать на месте для его и как добавлять.
