### ISSUE TITLE
Может быть имеет смысл влить библиотеки GammaBinding в основной репозиторий

### ISSUE THREAD

**Issue by Gankov** [QualitySolution/QSProjects#334]
Когда этот биндинг создавался, была идея что он будет развиваться независимо.
Мне кажется сейчас практически нет никакого смысла держать эту часть кода в отдельном репозитории. 
Скорее наоборот это создает проблемы с версионированием, при больших изменениях в GammaBinding надо создавать ветки дополнительно и в этом репозитории тоже.

Что думаете может перенесем код в репозиторий QSProjects?

**Comment by Enzogord** [comment]
Согласен, так будет удобнее.

**Comment by Gankov** [comment]
Как думаешь прям в корень положить? Или подпапку Gamma сделать?

**Comment by Enzogord** [comment]
Я бы предложил сделать папку Binding, и туда все
