### ISSUE TITLE
Лишний интерфейс IPage?

### ISSUE THREAD

**Issue by Enzogord** [QualitySolution/QSProjects#41]
Сейчас в INavigationManager используется интерфейс для страницы IPage, который внутри приводиться к IInternalPage для внутреннего управления страницей из менеджера. То есть страницу уже не заменить ни на какую другую реализацию, потому что нет информации об IInternalPage. Хочу убрать интерфейс оставив только сам класс Page и Page < TViewModel > , с internal свойствами для внутренного управления и public свойствами который были для IPage.
Я мог чтото упустить, но мне кажется с классом будет проще.

**Comment by Gankov** [comment]
Да не заменить из внешней сборки, но вполне можно заменить в сборках входящих в доверенные внутрение. Идея может быть и не плохая.
И может быть даже правильная, но давай сначала устаканим работу этого интерфейса со всех сторон, а потом уже будем упрощать, это.
Потому что есть следующие соображения:
- В коде которорый у меня уже лежит в стеше, этот класс уже разбит на 2 класса с одним базовым. И я туда добавил еще один интерфейс для страниц открытых в напрямую через Tdi напрямую, не имеющий ViewModel как таковую. Это сделано для специального режима менеджера навигации который работает в смешеной среде со старыми и новыми вкладками. Для того чтобы новыя вкладка могла быть открыта, как подчиненая для старой кладки без ViewModel. Я это все по выносил в отдельные интрефейсы и классы совместимости, чтобы потом можно было проще удалить... В целом это практически не влияет на твое предложение, Но реализации Page уже две.
- Стоит предположить что какие то другие менеджеры навигации захотят иметь свои реализации страниц с сохранением какой-то внутренней информации для своей работы. 
- Если главная задача насамом деле в том чтобы избавиться от интерефейса IInternalPage тогда уж лучше просто в место в менеджере приводить напрямую к page и все, то есть избавлятся от IInternalPage, а не от IPage. Тогда каждый менедже навигации сможет по своему класс реализовывать. Но этом мешает следующий пункт \/
- Вообще то класс Page это дженерик класс. Как их хранить и работать с ними в менеджере если не будет не дженерик интерфейса?

**Comment by Gankov** [comment]
Ну да если сделать PageBase то можно приводить к нему... А расширения делать только его.
Ты практическую какую то проблему сейчас решаешь?
Я бы просто подождал с предложением.

**Comment by Enzogord** [comment]
Ну я сейчас пытаюсь реализовать менеджер навигации универсальный для обоих проектов, и это так, улучшения которые сразу попадаются и хочеться поменять, не мешает особо, можно и попдождать, чтобы у тебя ничего не запуталось.

**Comment by Enzogord** [comment]
> * Вообще то класс Page это дженерик класс. Как их хранить и работать с ними в менеджере если не будет не дженерик интерфейса?

Page : Page<ViewModelBase> { } должен подойти, пока не могу запустить првоерить, но среда не ругается

**Comment by Gankov** [comment]
Я думал наоброт ` Page < TViewModel >  : PageBase `
Ибо тот что реализует дженерик добавляет в ее только типизированное свойство въю модели...
В твоем варианте смыла нет вообще в дженерике. Так как у тебя тип все время будет ViewModelBase для все страниц.
