### ISSUE TITLE
Улучшения в IInteractiveService

### ISSUE THREAD

**Issue by Enzogord** [QualitySolution/QSProjects#64]
Предлагаю убрать из сервиса не нужные зависимости IInteractiveMessage и IInteractiveQuestion.
Уже не помню зачем они именно так добавлялись, но выглядят они лишними.
Сделать реализацию их функционала сразу в сервисе IInteraticeService

**Comment by Gankov** [comment]
Я вчера тоже про это думал.
Изначально IInteractiveMessage и IInteractiveQuestion разделены специально.
Потому что предполагалось что они будут в основном передаваться в доменную модель или любой другой код, который реализует некую бизнес логику, при этом при определенных обстоятельствах, может заходеть как то провзаимодействовать с пользователей.

И с этой целью разделение на 2 интерфейса дает, огромный плюс, просто передавая в бизнес метод один или другой интерфейс, сразу же в вызове видно, как этот метод может поровзаимодействовать с внешним миром. Он может только сообщить чегото. Или может спросить. То есть ждет ответа, потому что в первом случае, можно тупо в лог сообщения скидывать. А во втором готовить авто ответ.

Но использование этого в IInteraticeService выглядит преусложненным. Я сначала подумывал просто в интерфейс добавить короткие вызовы аля ShowMessage.

Но сейчас понимаю что нужно сделать не так. Вообще то интерфейсы  IInteractiveMessage и IInteractiveQuestion изначально разрабатывались так чтобы они не персекались вызовами, а поэтому могли быть реализованы одним объектом.
Поэтому считаю что интерфейс IInteraticeService, должен просто наследоваться\реализовывать интерфейсы  IInteractiveMessage и IInteractiveQuestion. Если нам надо где-то потребовать только возможность задать вопрос мы как и раньше предеаем IInteractiveQuestion, если надо требовать и то и другое IInteraticeService. Это кстати даст возможность в тот код который ждет IInteractiveQuestion, или IInteractiveMessage передать объект реализующий более общий интерфейс. Как тебе идейка?

**Comment by Enzogord** [comment]
> Поэтому считаю что интерфейс IInteraticeService, должен просто наследоваться\реализовывать интерфейсы IInteractiveMessage и IInteractiveQuestion. Если нам надо где-то потребовать только возможность задать вопрос мы как и раньше предеаем IInteractiveQuestion, если надо требовать и то и другое IInteraticeService. Это кстати даст возможность в тот код который ждет IInteractiveQuestion, или IInteractiveMessage передать объект реализующий более общий интерфейс. Как тебе идейка?

Отлично, мне нравиться, самый универсальный способ
